name: API Call and File Push

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  api_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"

    - name: API Call and File Push
      run: |
        API_URL='https://script.google.com/macros/s/AKfycbyrh3wEuvmOlCu2iZaA393m8WMUZHc1555RqtQp6dg4GCy_xTA936tvhydSt864VblCJg/exec?sheet=raw&action=read'
        FILE_FORMAT='daa_$(date +\%d-\%m-\%Y).json'
        FILE_PATH="${GITHUB_WORKSPACE}/${FILE_FORMAT}"

        # Make API call and save response to file
        curl -sL "${API_URL}" > "${FILE_PATH}"

        # Commit and push the file to GitHub
        git add "${FILE_PATH}"
        git commit -m "Add API response file ${FILE_FORMAT}"
        git push origin main  # Replace 'main' with your branch name
